"""create initial tables

Revision ID: 2e8bfd41ea46
Revises: 
Create Date: 2026-09-25 20:19:45.368574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e8bfd41ea46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests_log',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_identity', sa.String(), nullable=False),
    sa.Column('provider_model', sa.String(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('security_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('threat_category', sa.String(), nullable=False),
    sa.Column('action_taken', sa.String(), nullable=False),
    sa.Column('evaluator_reasoning', sa.Text(), nullable=True),
    sa.Column('prev_hash', sa.String(), nullable=True),
    sa.Column('record_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests_log.request_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_events')
    op.drop_table('requests_log')
    # ### end Alembic commands ###
