"""align existing schema drift

Revision ID: 3147fb0ad8df
Revises: acdee238fb9a
Create Date: 2026-10-03 01:06:02.557180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3147fb0ad8df'
down_revision: Union[str, None] = 'acdee238fb9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approval_requests', 'action_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index('ix_approval_requests_agent_time', table_name='approval_requests')
    op.create_index('ix_approval_requests_agent_time', 'approval_requests', ['agent_id', sa.text('requested_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_approval_requests_agent_time', table_name='approval_requests')
    op.create_index('ix_approval_requests_agent_time', 'approval_requests', ['agent_id', 'requested_at'], unique=False)
    op.alter_column('approval_requests', 'action_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
