"""change all request_ids to string

Revision ID: 583c11ef6983
Revises: 2e8bfd41ea46
Create Date: 2026-09-26 15:42:34.900576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '583c11ef6983'
down_revision: Union[str, None] = '2e8bfd41ea46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests_log', 'request_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('security_events', 'request_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
   ## op.drop_constraint('security_events_request_id_fkey', 'security_events', type_='foreignkey') ##
   #     # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('security_events_request_id_fkey', 'security_events', 'requests_log', ['request_id'], ['request_id'])
    op.alter_column('security_events', 'request_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('requests_log', 'request_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
