"""add tenant_settings table

Revision ID: 73f49120c3d6
Revises: 86b6203fa9f2
Create Date: 2026-09-30 09:12:14.116556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73f49120c3d6'
down_revision: Union[str, None] = '86b6203fa9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_settings',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('inbound_scanner_enabled', sa.Boolean(), nullable=False),
    sa.Column('pii_redaction_enabled', sa.Boolean(), nullable=False),
    sa.Column('judge_enabled', sa.Boolean(), nullable=False),
    sa.Column('alert_sounds', sa.Boolean(), nullable=False),
    sa.Column('email_alerts', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_settings')
    # ### end Alembic commands ###
