"""add totp_credentials table

Revision ID: 86b6203fa9f2
Revises: 950126facc34
Create Date: 2026-09-29 20:53:23.038167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86b6203fa9f2'
down_revision: Union[str, None] = '950126facc34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('totp_credentials',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('secret', sa.String(length=64), nullable=False),
    sa.Column('recovery_codes_hash', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('totp_credentials')
    # ### end Alembic commands ###
